apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark-app-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps"]
  verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]