apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-app-role-binding
subjects:
- kind: ServiceAccount
  name: spark-app-sa
roleRef:
  kind: Role
  name: spark-app-role
  apiGroup: rbac.authorization.k8s.io